# Generated by Django 3.2.16 on 2022-12-03 07:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cart_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=20)),
                ('member_sex', models.CharField(choices=[('0', '女性'), ('1', '男性'), ('2', '不選擇')], help_text='輸入性別', max_length=1)),
                ('member_addr', models.CharField(max_length=50)),
                ('member_email', models.EmailField(max_length=254)),
                ('member_birth', models.DateField(blank=True)),
                ('member_register_date', models.DateField(auto_now_add=True)),
                ('member_login', models.DateField(auto_now_add=True)),
                ('member_pwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_time', models.TimeField(auto_now_add=django.utils.timezone.now)),
                ('rent_time', models.TimeField()),
                ('order_status', models.CharField(choices=[('0', '配送中'), ('1', '尚未配送'), ('2', '已送達')], help_text='商品狀態', max_length=1)),
                ('order_price', models.PositiveIntegerField()),
                ('return_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('payment', models.CharField(choices=[('c', '信用卡'), ('t', '轉帳')], default='c', help_text='選擇付款方式', max_length=1)),
                ('trans_time', models.DateTimeField(auto_now_add=True)),
                ('bank_id', models.CharField(blank=True, max_length=7, validators=[django.core.validators.MinLengthValidator(7)])),
                ('card_type', models.CharField(choices=[('v', 'VISA'), ('m', 'Master')], max_length=1)),
                ('card_id', models.CharField(blank=True, max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('dueD_date', models.CharField(blank=True, max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra large')], default='m', help_text='服裝尺碼', max_length=2)),
                ('product_price', models.PositiveIntegerField()),
                ('product_fine', models.PositiveIntegerField()),
                ('product_type', models.ManyToManyField(help_text='服裝類型', to='leasing.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_status', models.CharField(choices=[], help_text='Item 狀態', max_length=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leasing.product')),
            ],
        ),
    ]
