# Generated by Django 3.2.16 on 2022-12-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
