# Generated by Django 4.1.3 on 2022-12-14 07:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_alter_order_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('due_day', models.DateTimeField(auto_now_add=True)),
                ('is_due', models.BooleanField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasing.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Duerecord',
        ),
    ]
