# Generated by Django 3.2.16 on 2022-12-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_auto_20221203_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_login',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_pwd',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_register_date',
        ),
    ]
