# Generated by Django 3.2.16 on 2022-12-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_alter_cart_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_phone',
            new_name='member_phne',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('0', '配送中'), ('1', '尚未配送'), ('2', '已送達'), ('3', '訂單不成立')], help_text='商品狀態', max_length=1),
        ),
    ]
