# Generated by Django 3.2.16 on 2022-12-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0003_auto_20221215_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_phne',
            new_name='member_phone',
        ),
    ]
