# Generated by Django 4.1.3 on 2022-12-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0003_returnrecord_delete_duerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrecord',
            name='due_day',
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='due_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
