# Generated by Django 4.1.3 on 2022-12-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0003_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
