# Generated by Django 4.1.3 on 2022-12-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0003_alter_product_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[("0", "刪除"), ("1", "保留")],
                default="1",
                help_text="Type 狀態",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="type",
            name="type_status",
            field=models.CharField(
                choices=[("0", "刪除"), ("1", "保留")],
                default="1",
                help_text="Type 狀態",
                max_length=1,
            ),
        ),
    ]
