# Generated by Django 4.1.3 on 2022-12-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0004_rename_member_phne_member_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnrecord',
            old_name='due_date',
            new_name='return_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('0', '配送中'), ('1', '尚未配送'), ('2', '已送達'), ('3', '訂單不成立')], default='1', help_text='商品狀態', max_length=1),
        ),
    ]
