# Generated by Django 4.1.3 on 2022-12-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0006_alter_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_count',
            new_name='product_count',
        ),
    ]
