# Generated by Django 4.1.3 on 2022-12-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0006_remove_item_item_size_product_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_time',
            new_name='order_datetime',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='rent_time',
            new_name='rent_datetime',
        ),
        migrations.RenameField(
            model_name='returnrecord',
            old_name='return_date',
            new_name='return_datetime',
        ),
    ]
