# Generated by Django 3.2.16 on 2022-12-17 07:37

import django.core.validators
from django.db import migrations, models
import leasing.models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0007_rename_order_time_order_order_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_datetime',
            new_name='order_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='rent_datetime',
            new_name='rent_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_size',
        ),
        migrations.AddField(
            model_name='item',
            name='item_size',
            field=models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra large')], default='m', help_text='服裝尺碼', max_length=2),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(3), leasing.models.only_int]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_id',
            field=models.CharField(blank=True, help_text='前三碼 銀行, 後四碼 分支機構', max_length=7, validators=[django.core.validators.MinLengthValidator(7), leasing.models.only_int]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_id',
            field=models.CharField(blank=True, help_text='16碼', max_length=16, validators=[django.core.validators.MinLengthValidator(16), leasing.models.only_int]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.MinLengthValidator(4), leasing.models.only_int]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='valid_number',
            field=models.CharField(blank=True, max_length=3, validators=[django.core.validators.MinLengthValidator(3), leasing.models.only_int]),
        ),
    ]
