# Generated by Django 4.1.3 on 2022-12-17 09:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import leasing.models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0007_rename_order_time_order_order_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leasing.product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_id',
            field=models.CharField(blank=True, help_text='前三碼 銀行, 後四碼 分支機構', max_length=7, validators=[django.core.validators.MinLengthValidator(7), leasing.models.only_int]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_id',
            field=models.CharField(blank=True, help_text='16碼', max_length=16, validators=[django.core.validators.MinLengthValidator(16), leasing.models.only_int]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.MinLengthValidator(4), leasing.models.only_int]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='valid_number',
            field=models.CharField(blank=True, max_length=3, validators=[django.core.validators.MinLengthValidator(3), leasing.models.only_int]),
        ),
    ]
