# Generated by Django 4.1.3 on 2022-12-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0008_alter_item_product_alter_transaction_bank_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rent_datetime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='returnrecord',
            name='return_datetime',
            field=models.DateField(auto_now=True),
        ),
    ]
