# Generated by Django 3.2.16 on 2022-12-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0008_alter_item_product_alter_transaction_bank_id_and_more'),
        ('leasing', '0008_auto_20221217_1537'),
    ]

    operations = [
    ]
