# Generated by Django 4.1.3 on 2022-12-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0008_rename_dued_date_transaction_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_price',
        ),
    ]
