# Generated by Django 4.1.3 on 2022-12-12 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0009_remove_order_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='valid_number',
            field=models.CharField(blank=True, max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
