# Generated by Django 4.1.3 on 2022-12-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0008_auto_20221217_1537"),
        (
            "leasing",
            "0009_alter_order_order_datetime_alter_order_rent_datetime_and_more",
        ),
    ]

    operations = []
