# Generated by Django 4.1.3 on 2022-12-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0009_merge_20221217_2140"),
        ("leasing", "0010_merge_20221217_2158"),
    ]

    operations = []
