# Generated by Django 4.1.3 on 2022-12-13 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0011_alter_transaction_bank_id_alter_transaction_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_id',
            field=models.CharField(blank=True, help_text='16碼', max_length=16, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
