# Generated by Django 4.1.3 on 2022-12-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0012_alter_transaction_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_time',
            field=models.DateTimeField(),
        ),
    ]
