# Generated by Django 4.1.3 on 2022-12-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0013_alter_order_return_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
