# Generated by Django 4.1.3 on 2022-12-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0016_product_product_description_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rent_time',
            field=models.DateTimeField(),
        ),
    ]
